name: jetleaf_resource
description: Resource management module for JetLeaf â€” handles caching and rate limiting efficiently.
version: 1.0.5

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_resource
issue_tracker: https://github.com/jetleaf/jetleaf_resource/issues
documentation: https://jetleaf.hapnium.com/docs/resource

topics:
  - caching
  - rate-limiting
  - jetleaf
  - performance
  - resources

keywords:
  - jetleaf
  - cache
  - throttling
  - limits
  - resource-management

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.0.6
  jetleaf_logging: ^1.0.6
  jetleaf_pod: ^1.0.6
  jetleaf_core: ^1.0.6
  jetleaf_env: ^1.0.6

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0